version: '3.9'

services:
  postgres:
    container_name: devbookdb
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=devbookdb
    
